version: '3'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/my_database
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
